### ISSUE TITLE
Game Page - Map Showing

### ISSUE THREAD

**Issue by Wans-G** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_007#32] opened 2024-11-10 00:26 UTC
As
a user,
I want
a map which contains the same apperance as the other players in the same room,
So that
all players can interact with the same game environment coherently.

**Comment by bjohnson66** [comment] 2024-12-02 23:30
possible duplicate of another story, but that is ok.

**Closed** 2024-12-13 01:54 UTC
Labels: SP: 2, Priority: Normal, State: To Do, Feature: Game Page (Map and Stats)
